### PR TITLE
jobs ui pages

### PR DESCRIPTION
**Pull request by mazma1**
- Jobs landing page
- Register pages
- Post A Job page
- Login page
- Organization account page
- Success Message page

### CODE REVIEW

**Review by temilolakutelu — COMMENTED** [review]
Nice work Mary,
Please see my feedback below;

- Menu name according to design is 'Job Opportunities' not 'Jobs'
- The page title and subtitle text font size should be reduced and the margin also reduced. The top part of the first row of jobs list should show on page load(see the attached screen for clarity).
jobs1
-On view pop up, active button is different from the XD design(see attached)
jobs2
- On jobs list, Font size and font-weight job title differs from the XD design provided
-On register page, page background is different from XD design.
- Animation on Proceed button not implemented
- Animation on Register button on Contact details form not implemented
-Success modal not implemented
-Box shadow on 'Post A Job' button not implemented
-On Post a job form, button colour, animation and general page margin is different from the XD design provided.(see attached)
jobs3
-There is no login form

**Comment by mazma1** [comment]
Thanks for reviewing, Lola.
1) The page title and subtitle text font size should be reduced  and the margin also reduced:
I didn't style these, I reused existing classes of other page heros for consistency sake. But I'll go ahead and reduce them.

2) The top part of the first row of jobs list should show on page load:
This is still not clear with the screenshot.

3) Active button is different from the XD design(see attached):
That's the point, I don't think that is meant to be a button but rather a tag that shows if a job is active or closed (correct me if I'm wrong). So I styled it differently so as not to confuse users.

    Think about it, what is the purpose of an "Active" button? What should it do if a user clicks on it?

4) There is no login form:
It didn't show up because of a routing conflict. Fixed now.

5) On jobs list, Font size and font-weight of job title differs from the XD design provided:
The font size is correct but for some reason, the applied font weight doesn't seem to make any visual difference. I don't know if it has to do with the font but I don't know what to do about that.

6) On register page, page background is different from XD design:
What background are you seeing? What I have is plain like in the design.

7) On Post a job form, button colour, animation and general page margin is different from the XD design provided:
Not sure what general page margin is about but I was confused on why we have different button styles for similar web pages. Say I update the color to the pink in the design (which has been used in several other pages), the existing style on hover will be different from what is on this page.

7) On button animations:
I think we need to formalize our button animations/hover styles, they are all over the place at the moment. For the Jobs buttons however, my CSS animations skill is 0 so I wasn't clear how to add that paparrazi, lol. I'll appreciate any pointers

**Comment by mazma1** [comment]
I'll work on the missing Success modal

**Comment by temilolakutelu** [comment]
Kindly resolve conflicts.

**Review by temilolakutelu — COMMENTED** [review]
Kindly resolve conflict.
PS: try not to overwrite the current code on the develop branch

**Comment by mazma1** [comment]
Branch is updated now

**Comment by temilolakutelu** [comment]
Hi, kindly resolve conflicting files

**Pull request merged**
