### PR TITLE
Feature/job opportunity

### PR DESCRIPTION
**Pull request by maryam-olabisi**
Company's registration
Log in
Post job information

### CODE REVIEW

**Review by temilolakutelu — COMMENTED** [review]
- On register form, on contact details form submit button click, nothing happens as it just reloads the form. Apparently, some form validation errors do not show.
-On job details form, specialization dropdown should be in alphabetical order.

**Comment by temilolakutelu** [comment]
- Please populate the specialization and Organization industry dropdown from admin end.
- Does this cover all feedback changes?

**Review by mazma1 — COMMENTED** [review]
@maryam-olabisi well done on getting this out! 💪🏽 💪🏽

I tried registering to post a job but I kept getting this error no matter what email/phone number I enter
Screenshot 2020-12-04 at 06 53 04

**Comment by maryam-olabisi** [comment]
> @maryam-olabisi well done on getting this out! 💪🏽 💪🏽
> 
> I tried registering to post a job but I kept getting this error no matter what email/phone number I enter
> Screenshot 2020-12-04 at 06 53 04

FIxed

**Comment by maryam-olabisi** [comment]
> * Please populate the specialization and Organization industry dropdown from admin end.
> * Does this cover all feedback changes?

- Feedback changes covered

- Added 'other' to specialization and organization industry

**Comment by temilolakutelu** [comment]
2. I can see no options were added, it's up to your team to add those you know? can't be the admin

7. no profile icon has been added for them to know they're now signed in and something to easily lead them to their own profile (they should still be able to view other job posts on the page rather than just seeing their dashboard).  - it's needed for good UX

8. I created a job, went to the admin end and signed in twice but can't see the job posted so as to review it

9. The job detail view is still too large and takes up much space on the screen, can we re-create that to a square shaped design centred right on top the particular job user is checking out

Other issues:
1.All URL fields : can't we add a placeholder that lets them know they need to add the "https" to it, not everyone is smart enough to know it needs to be there even with the error msg

2. the phone number field has to accommodate other country codes, I can't see a dropdown (best way to tackle this is create a field for countries and when they select their country, it auto fills their country code for phone numbers)

3. The text showing "under review" can be a little bit bolder or be a small button in red with text "under review" and when it's live, changes to a green button with text "LIVE"

4. what's the provision for when a job is expired i.e how do we show on their DB that their posted job has passed it's application deadline and we've made it inactive?
I'm suggesting something similar to No.3 - the button changing to grey with text "expired"

5. there's no "log out" link/button on the site/user dashboard hence the importance of No7 i pointed above.

**Comment by mazma1** [comment]
Stale. Need to recreate review app

**Review by temilolakutelu — COMMENTED** [review]
Good job on this. However, I have just a few corrections/clarifications;
- Why do we have a closed jobs tab on the jobs page? I don't think it is necessary.
-Under published jobs, the pagination is a bit confusing
cor1
-Organisation industry field dropdown on the register form needs more options.
-There is a prompt on Logout; I suggest we use a toast like the one used for feedback form submission.

**Comment by temilolakutelu** [comment]
Also, the job view modal is not responsive on mobile view. If it's going to be scrollable, then the scroll bar should be visible

**Comment by mazma1** [comment]
@temilolakutelu thanks for reviewing:
1) I'll remove the "Closed Jobs" part, I initially thought it was necessary.
2) That pagination thing is the main reason I have not shared the link to the broader group. I don't see it locally but somehow it shows up on Heroku! I'll try different browsers and see if I'm able to reproduce it.
3) You said you were going to give me more options to add???
4) I don't see the prompt you're referring to on Logout
5) That was probably another piece that was broken with all the changes that have been made. I'll check it out 😒😒

**Comment by temilolakutelu** [comment]
3. I actually said, we need to add more options to the Organisation Industry list, not that I will give more options.
4. &5. Sorry, I meant there should be a prompt. Presently, it is non-existent.
Thanks.

**Review by temilolakutelu — APPROVED** [review]

**Pull request merged**
